# Generated by Django 5.0.14 on 2026-06-29 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WarehouseZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "max_weight_capacity",
                    models.DecimalField(
                        decimal_places=2, help_text="Max capacity in kg", max_digits=10
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=100)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "unit_weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weight of a single unit in kg",
                        max_digits=6,
                    ),
                ),
                ("low_stock_threshold", models.IntegerField(default=10)),
                (
                    "warehouse_zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_items",
                        to="inventory.warehousezone",
                    ),
                ),
            ],
        ),
    ]
